### ISSUE TITLE
Items dropped no longer work

### ISSUE THREAD

**Issue by KingAbyx** [ThinkInvis/RoR2-TinkersSatchel#10]
### Describe the Bug
As of this day there is an item drop with name "TinkersSatchel_GOLDENGEAR_NAME" and the description "TinkersSatchel_GOLDENGEAR_DESC" it does not give armour or do anything else. This persists between restarts and it seems to drop quite frequently (Three times in two under 10 minute runs)

### To Reproduce
Get the item as a drop in game

### Expected Behavior
Item should have a name and description and should also work

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/7738391/LogOutput.log)

### Additional Context
Still worked a few days ago. Also I didn't get the mimic dropped yet so idk if that works or not

**Comment by ThinkInvis** [comment]
This is an IL hook incompatibility with KingKombatArena.

**Comment by ThinkInvis** [comment]
KingKombatArena appears to be unmaintained and currently fails to load. Closing issue as moot, until such time as said mod is restored.
