### ISSUE TITLE
Sturdy Mug bugs Nano Spear

### ISSUE THREAD

**Issue by martinvillarreal5** [ThinkInvis/RoR2-TinkersSatchel#12]
### Describe the Bug
Extra Proyectile from sturdy mug item seems to colide with the original proyectile from nano spear, making it explode

### To Reproduce
Just proc the sturdy mug proyectile

### Expected Behavior
The proyectiles shouldn't collide with each other

**Comment by ThinkInvis** [comment]
Fixed in 661ff59468e073d96d9a0add35786c4d30580fbf.

**Comment by martinvillarreal5** [comment]
Nice!
