### ISSUE TITLE
Not an issue more of a selection of ideas/requests

### ISSUE THREAD

**Issue by EnderGrimm1** [ThinkInvis/RoR2-TinkersSatchel#2]
Theres not a mean of me posting something like this anyway

New Drones

Laser Drone - Shoots Lasers
Tesla Turret - A walking Tesla Coil
Decoy Turret - Draws enemies towards it then explodes
Shotgun Drone - Fires a Spread

White Items

Sherbert - Whenever you take damage from an enemy gain a short burst of speed and jump height

System Refinements - White - Improves basic functions of drones and turrets (purchasable ones not engineers)
Gunner Drone and Minigun Turret - Damage increased by 5%. {Stacks increase my 2%}
Healing Drone - Healing amount increased by 5%  {Stacks increase my 2%}
Missile Drone - Increases number of rockets fired per volley by +1 {Stacks increase amount by +1}
Prototype - Increase Armour by 5. (Stacks +5)
Flamer - Increase burn stacks applied.
Laser - faster recharge.
Tesla - Increase range.
Decoy - Increase explosion damage and radius.
Shotgun - add more pellets.

Cat's Eye Gem - Gain increased attack speed and damage after opening a chest or using a shrine

Green Items

Drone Self Repair Kit - Green - All drones rapidly heal when out of combat. 10% healing per sec. (Stacking +5% Healing)

Emergency Thruster Unit - Green - Drones will fly/run into nearby enemies on death and explode in a aoe of 5m dealing 100% damage. (Stacks +50% damage)

Red Items

Keepsake Box - Gain 5% damage for each unique item you are holding

Lunar Items

Steel Anvil - Gain a flat damage boost for each scrap you have

Equipment

Dog Treat - for the next minute the next nonboss enemy in your crosshairs fights for you

**Comment by ThinkInvis** [comment]
I'm not currently taking content requests for this mod -- it's more of a place to put my own ideas which wouldn't be worth making an entire new repository + Thunderstore listing for each. The ideas channel in the Risk of Rain 2 Modding Discord server is a better place to make this kind of suggestion; you could also try creating a mod yourself (with which people in said server would be happy to help!).
