### ISSUE TITLE
Pulse Monitor + Engineer Turret NRE.

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-TinkersSatchel#22]
### Describe the Bug
Pulse monitor causes NREs when placing Engineer turrets.

### To Reproduce
1. Play Engineer
2. Obtain Pulse Monitor
3. Place a Turret
4. Look at console

### Expected Behavior
I dunno really, since engineer turrets *technically* inherit equipment, but it only really matters for aspects? 
Not sure if it'd be even possible to have the equipment on your turrets trigger from Pulse.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8346590/LogOutput.log)

**Comment by ThinkInvis** [comment]
Fixed by ad4b14ea9bacb005889e5fbef50ed8ced2b759d2.
