### ISSUE TITLE
Armor Crystal and Armor Prism

### ISSUE THREAD

**Issue by kking117** [ThinkInvis/RoR2-TinkersSatchel#23]
### Describe the Bug
Armor Crystal does not grant armor but still stacks the respective buff.
Armor Prism gives twice the armor than what the in-game description and buff displays.

### To Reproduce
There isn't any real steps beyond "Get a copy of the item.".

### Expected Behavior
Armor Crystal:
For armor to increase with stacks of the buff.

Armor Prism:
Having an inventory of 1 Armor Prism and nothing else grants 500 armor.

### Console Log
This log is of 2 different runs on Rainstorm difficulty.
The first run I create a pickup for the Armor Crystal, then give myself 1000 gold and let enemies kill my character.
The second run I create a pickup for the Armor Prism, then let enemies kill my character.

[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8346829/LogOutput.log)

### Additional Context
Tested on r2modman 3.1.27 with these additional mods:
BetterUI 2.5.3
DebugToolkit 3.7.1

**Comment by ThinkInvis** [comment]
Fixed by 3a9220de762221a29b0f1f24e20b556d6da1c1b2.
