### ISSUE TITLE
Cardboard Box in multiplayer

### ISSUE THREAD

**Issue by SirTinyHead** [ThinkInvis/RoR2-TinkersSatchel#24]
### Describe the Bug
Using cardboard box has weird interactions in multiplayer. No matter who uses it only host can see the changes. Using printers as someone other than the host will still require you to go to the original printer location but the items will appear where it was moved to.

### To Reproduce
1. Start a multiplayer lobby (done on simulacrum mode when we did it)
2. Obtain cardboard box
3. When using the cardboard box nothing will appear to change except for the lobby host

### Expected Behavior
We would hope that for all players the interactable would move and function as intended in it's new location.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8361334/LogOutput.log)

Log is as host.

**Comment by ThinkInvis** [comment]
Found the cause: I accidentally structured the networking to only work right on dedicated servers :(
