### ISSUE TITLE
Add Shock to Triskellion Brooch

### ISSUE THREAD

**Issue by gaforb** [ThinkInvis/RoR2-TinkersSatchel#25]
Instead of stun why not have it apply shock, completing the elemental trifecta and adding a much-needed source of shock to the game. Or just add shock as another thing it can proc in addition to stun, but that does clash with the "Tri" aspect

Also, some adjustments to the config seem reasonable:

- The base chance to proc defaults to 9 (100%) instead of the intended 0.09 (9%)
- Separate base proc chance from stack proc chance so it can be kept at a flat value
- Remove the limit on base / stack damage (cannot be set higher than 100% at the moment)

**Comment by ThinkInvis** [comment]
Triskelion Brooch is an Artificer-themed item: Artificer has stun, freeze, and ignite available through skills -- even all at once -- but not shock. All of the former are also available from at least one item source, while the latter *only* exists on Captain M2; so switching stun to shock would reduce this item's effectiveness by 1/3 on any other character, no matter how many other items they have. I'll make shock count as stun for the purposes of this item, but that's the most I'm willing to change on this front.

The proc chance isn't implemented correctly: it should be a 0-100 value (as `Util.CheckRoll` uses), but it's incorrectly clamped to/displayed in logbook as 0-1 at the moment, and not actually checked before proccing.

**Comment by ThinkInvis** [comment]
Fixed/implemented in above commits.
