### ISSUE TITLE
When mod is enabled, Enforcer mod's shotgun particles don't display half the time

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-TinkersSatchel#31]
### Describe the Bug
When TinkersSatchel is enabled, the particles from Enforcer's gun will fail to display around half the time. The behavior is inconsistent.

### To Reproduce
1. Choose Enforcer.
2. Fire your shotgun.
3. Destroy your enemies with invisible psychic energy.

### Expected Behavior
Shotgun Fire Pellets

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8403035/LogOutput.log)

This is from an otherwise clean profile.

**Comment by PollyEdaline** [comment]
To be more clear, I genuinely have no idea how to consistently reproduce the bug. I know for sure that enabling this mod causes the bug, and disabling it fixes it.

**Comment by ThinkInvis** [comment]
Not Enforcer-specific. *Something* is causing effect prefabs to go missing, even while all items are disabled. Trying to track this down now.
