### ISSUE TITLE
Item Drone + Mystic's items incompatability.

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-TinkersSatchel#33]
### Describe the Bug
If an item drone obtains marwan's ash by any means (being summoned in, giving it the item), and then it levels up, it will keep giving copies of marwan's ash to the player, resulting in infinite stacks of marwan's ash.

### To Reproduce
1. Start a run
2. Obtain Marwan's ash
3. give marwan's ash to an item drone
4. level up to the level that marwan's ash turns into marwan's light

### Expected Behavior
to just give one fake copy of marwan's ash/light/weapon

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8416902/LogOutput.log)

### Additional Context
Add any other context about the problem here (screenshots, etc.).

**Comment by ThinkInvis** [comment]
Mystic's Items needs to add a soft dependency on TILER2 and ignore fake items while performing an upgrade. There will be an update to TILER2 soon that makes this easier (191aa6b3f0d359fe6d5023b29988d6858d11a3a1).

**Comment by ThinkInvis** [comment]
Fixed in https://github.com/TheMysticSword/MysticsItems/commit/3870c4cefc1289be4d0a4bc9769f7320f633ae20.
