### ISSUE TITLE
Negative Feedback Loop applies to fall damage, which can kill you

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-TinkersSatchel#37]
### Describe the Bug
Fall damage is applied to Negative Feedback Loop. This means that if you take enough damage at once, Negative Feedback Loop's DoT will kill you.

### To Reproduce
1. Get at least one NFL.
2. Fall down and break your legs.
3. Your body will fail you.

### Expected Behavior
Even if this isn't technically a bug, this ends up making NFL a dangerous pickup if you are either prone to falling off of things or playing a character that takes fall damage often for any reason. NFL's effect should not apply to fall damage at all.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8459609/LogOutput.log)

**Comment by ThinkInvis** [comment]
Already had this in a notes file. I was going to make it track nonlethal damage and pass that property through to the DoT ticks, but not proccing at all on nonlethal damage is probably a better solution.
