### ISSUE TITLE
Mostly Tame Mimic Bug

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-TinkersSatchel#4]
Mostly Tame Mimic is currently Mimicking items in absurd quantities, and items that aren't in the player's inventory.

Tiler2 version: 2.1.2
Classicitems version (if relevant): 4.5.0
Tinker's Satchel Version: 1.2.1

**Comment by ThinkInvis** [comment]
Can't reproduce; a console log from a run of the game where this bug occurred would be helpful.

**Comment by Coffe-e** [comment]
That's odd, now i'm not even having this bug?
I had deleted tinker's satchel yesterday, but when i redownloaded it it was fine?
then again I remembered that i forgot to remove Minirpclib if you ever do actually find this bug.
Although, I will continue to search for that within the quantity of mods i play in.

**Comment by Coffe-e** [comment]
Yeah, i can't seem to reproduce it after yesterday.
Yeah, sorry about that.
