### ISSUE TITLE
Sturdy Mug procs itself?

### ISSUE THREAD

**Issue by AshSuqs** [ThinkInvis/RoR2-TinkersSatchel#40]
Sturdy Mug when at 10+ stacks infinitely causes projectile spawns and locking animations. This was tested in multiplayer, I am unware if it happens in single player

Found this out while playing Rex and Acrid while encountering a mug printer, and for Rex it'd cause an infinite stream of primary fire. While for Acrid it would only apply the item to his AoE leap and at 10 stacks would prevent him from finishing the animation due to infinite looping of the poison splash lagging the game immensely.

I think the issue is that the Sturdy Mug is also procing on the projectiles it spawns instead of just the initial projectiles.

Sorry if this isn't detailed enough but I figured i'd atleast bring the issue to light.

**Comment by AshSuqs** [comment]
[Log file.txt](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8486928/Log.file.txt)

**Comment by ThinkInvis** [comment]
It's not immediately obvious what it is from that log, but something in your modlist is causing *major* networking issues (e.g. types of object that only the server knows about, but the clients should too). You might have had different modlists between client and server, which would be a definite cause of errors like this. You might also have a mod that isn't designed for multiplayer, or it could be a conflict between two or more mods.

2e91cddac1debf0139f1c65c2943394116ce4237 should prevent Sturdy Mug itself from causing further problems when issues like that are happening.
