### ISSUE TITLE
Macho Mustache doesn't obey Bonus config options

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-TinkersSatchel#41]
### Describe the Bug
Macho Mustache doesn't obey Bonus config options.

### To Reproduce
1. Have the Elite/Champ bonus set to whatever.
2. Game will treat Elites as 3 and Champions as 6 (or something).

### Expected Behavior
The default config even lists these as 2 and 4. Makes the item extremely strong late-game.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8477769/LogOutput.log)

**Comment by ThinkInvis** [comment]
Those are numbers to add to the count if an enemy is an elite and/or a boss; these, + being present and in combat/danger at all, are all counted separately. I'm unable to reproduce changes to these configs having no effect; they appear to work as intended.

**Comment by PollyEdaline** [comment]
I'll check again tomorrow on a clean profile and do some more testing. Perhaps I'm misunderstanding how the configs should work. I'll close this if it turns out I'm just a dumbass.

**Comment by PollyEdaline** [comment]
Turns out I'm just a dumbass.
