### ISSUE TITLE
Blacklist Equipment/Item Drones from Command Terminal

### ISSUE THREAD

**Issue by slaugaus** [ThinkInvis/RoR2-TinkersSatchel#43]
### Is your feature request related to a problem? Please describe.
I'm probably just salty, but Command Terminal shouldn't have a chance to give you a completely useless drone. It could at the very least tell me that it's an equipment/item drone and let me feed it something.

### Describe the solution you'd like
Equipment Drone and Item Drone should be removed from the list of drones Command Terminal can spawn.

### Describe alternatives you've considered
The Command Terminal pod should warn you somehow if it contains an Equipment/Item Drone and allow said drone to take your items like buying it normally would.

### Additional context
I used Command Terminal in a solo run and it gave me an empty Equipment Drone.

![image](https://user-images.githubusercontent.com/23143819/163310476-7b3a4cbb-f53c-4fd4-9aed-0b35e92bd4b9.png)

**Comment by ThinkInvis** [comment]
Item Drones and Equipment Drones summoned by this equipment should be given random items/equipment. That could be an equipment with no display rules (such as the ones added by this mod -- IDRs are hard ☹️).

Implemented regardless: 27f1e4fa2e7480f8a761c67b31b40292363d6768 exposes the list of valid summons to config.
