### ISSUE TITLE
Railgunner self-procs Shrink Ray

### ISSUE THREAD

**Issue by Alohacajun** [ThinkInvis/RoR2-TinkersSatchel#44]
### Describe the Bug
When playing RG and holding Shrink Ray, using Concussion Device on yourself will proc the shrink ray's ability-lockout effect.

Don't believe this is an intended effect; might have something to do with Concussion counting as damage? I believe her ability also triggers Safer Space's protection effect, could be something related to that.

**Comment by ThinkInvis** [comment]
This is unintentional, and appears to possibly be a base-game bug, or at least a misleading method name (item is triggered by a method called `OnHitEnemy`). Fixed by 70f3a85cc33b2bc2fac8c2244f37f3400de7d451.
