### ISSUE TITLE
Cannot figure out achievment

### ISSUE THREAD

**Issue by Dibbli** [ThinkInvis/RoR2-TinkersSatchel#45]
Hi, sorry if this isn't where I should be asking this, but I can't for the life of me figure out what the third musical instrument is for the achievement. Gorag's, Ukulele and ?
Thanks for the help, and great work on the mod :)

**Comment by ThinkInvis** [comment]
War Horn (check https://github.com/ThinkInvis/RoR2-TinkersSatchel/blob/master/ContentSummary.md). Please reserve this issues page for bug reports and non-new-content feature requests.
