### ISSUE TITLE
Item Drone in non-dedicated multiplayer servers

### ISSUE THREAD

**Issue by SirTinyHead** [ThinkInvis/RoR2-TinkersSatchel#46]
### Describe the Bug
Item Drone does not appear for non-hosts in non-dedicated servers

### To Reproduce
1. Find item drone as host
2. Ask another player to look at the item drone
3. They will not see it
4. If you buy it they will still not see it but it will give them the item effects still if they are near it

### Expected Behavior
Item drone appears with item display on it

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8493552/LogOutput.log)
I don't know if this is the right log but it should be. (Host log only)

**Comment by ThinkInvis** [comment]
Probably fixed as of 7205a0e4a455c77879c47c9c50278da1169d77a3, haven't been able to test in MP yet.

**Comment by ThinkInvis** [comment]
IIRC from a multiplayer session a few weeks back, this is fixed.
