### ISSUE TITLE
Overwriting the previous run in the Logbook

### ISSUE THREAD

**Issue by svrakiss** [ThinkInvis/RoR2-TinkersSatchel#47]
### Describe the Bug
Starting from version 1.14.0
Ending a classic run causes the previous classic run to be overwritten in the logbook Run History.
### To Reproduce
1. Launch game
2. Go to Run History to check most recent run.
3. Start a single player classic run.
4. Die/Obliterate/Win
5. Check the Run History. The previous classic run data is gone.

### Expected Behavior
The new run is added to the Run History. The information for the previous run is preserved.

### Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8507134/LogOutput.log)

### Additional Context
The deletion occurs even if the previous run used a working version of the mod (1.13.2).
I've tried this with all mods besides TinkersSatchel and its dependencies disabled. 
This has not been tested in the other play modes (multiplayer, Eclipse, etc.).

**Comment by ThinkInvis** [comment]
Can't reproduce. It might be happening only on the first run after updating the mod or something similar, as an existing item got renamed.

**Comment by svrakiss** [comment]
It was the morgue history limit.
