### ISSUE TITLE
Commando's Pulse (Primary) Please remove the bob/recoil effect

### ISSUE THREAD

**Issue by HoratioSanchez** [ThinkInvis/RoR2-TinkersSatchel#48]
The new skill on commando is very fun to use, but the bobbing up and down effect causes severe motion sickness for me, especially on high attack speeds. The screen constantly vibrating is very distracting and it forces me to use his other skills. Is there any way to remove that or make it optional?

**Comment by ThinkInvis** [comment]
Recoil is a major balance point for that skill, but I can try to brainstorm some alternatives.
