### ISSUE TITLE
Artifact of Safekeeping failure and NRE (possible incompat)

### ISSUE THREAD

**Issue by SkyeMors** [ThinkInvis/RoR2-TinkersSatchel#49]
### Describe the Bug
With a heavy modpack with Tinker's Satchel as the only (direct) item mod and the relevant Artifact enabled, the boss does not drop the items held for Safekeeping.

### To Reproduce
1. Use current pack
2. Start a match with the relevant Artifact enabled
3. Collect items, defeat boss
4. Behold lack of items, and logged NREs

### Expected Behavior
Boss should be dropping items held for Safekeeping. (It has only worked for me once, ever. It was glorious.)

### Console Log
Log (file, edited out NRE spam):
[log logged in log.txt](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8546461/log.logged.in.log.txt)

Log Excerpt (NRE that was spammed at moment of error):
```
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <469e86e97fa2467ebffe49bbd6086325>:IL_0021)
ThinkInvisible.TinkersSatchel.DelayLoot.Run_FixedUpdate (On.RoR2.Run+orig_FixedUpdate orig, RoR2.Run self) (at <860f9739c7ba46368c3a7eefe0036674>:IL_0096)
DMD<>?-2027156736.Hook<RoR2.Run::FixedUpdate>?1783331456 (RoR2.Run ) (at <9e43dfef54714b4cbd76df72508f90fe>:IL_0014)
DMD<>?-2027156736.Trampoline<RoR2.Run::FixedUpdate>?-2129729536 (RoR2.Run ) (at <f4528044cdc745a6bd918fe06907be5c>:IL_0020)
ThinkInvisible.TinkersSatchel.Defib.Run_FixedUpdate (On.RoR2.Run+orig_FixedUpdate orig, RoR2.Run self) (at <860f9739c7ba46368c3a7eefe0036674>:IL_0001)
DMD<>?-2027156736.Hook<RoR2.Run::FixedUpdate>?-1029145984 (RoR2.Run ) (at <87e2ad9e44e54d95a178251d76f16b57>:IL_0014)
```

### Additional Context

Remove the .zip (not unzip), had to add it so GitHub would accept it.

[MP Hella Modded XI - Return to Modded Fuckery_1650699429253.r2z.zip](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/8546462/MP.Hella.Modded.XI.-.Return.to.Modded.Fuckery_1650699429253.r2z.zip)

**Comment by ThinkInvis** [comment]
No idea what, specifically, is causing this. Best I can tell, another mod is destroying item droplets sometime between when they actually drop (AoS disables/pauses them immediately when this happens) and when AoS reawakens and moves them once the teleporter boss is defeated.

ab6af5cd9470493bb8e40ac2bddd923e46683f21 should prevent console errors when something like this happens, but it won't stop whatever is causing item droplets to go missing in the first place.
