### ISSUE TITLE
Gup Ray splits Void Boss

### ISSUE THREAD

**Issue by Alohacajun** [ThinkInvis/RoR2-TinkersSatchel#50]
### Spoilers for SotV Content!
<details>
  <summary>Show</summary>
  
  Gup Ray splits Voidling and appears to break the portal spawn to the parkour section after beating the 1st phase. Even after killing the "Gup'd" copis of Voidling, the portal to progress to phase 2 will not spawn, leaving the player stranded at the 1st stage.

**Comment by ThinkInvis** [comment]
Fixed by a91be0825ab7eb721f12b206fc730d28a75a5732.
