### ISSUE TITLE
Perhaps disable Voidwisp Hive in the Bazaar

### ISSUE THREAD

**Issue by SkyeMors** [ThinkInvis/RoR2-TinkersSatchel#51]
### Is your feature request related to a problem? Please describe.
A few times my friend and I have been kicked out of the Bazaar due to Voidwisp Hive activating and hurting the newt too much while browsing the items.

### Describe the solution you'd like
I'd like Voidwisp Hive to not activate in the Bazaar.

### Describe alternatives you've considered
It might be Equipment activating it, he has had Gesture of the Drowned a few times, so maybe a combination?

### Additional context
Meow.

**Comment by ThinkInvis** [comment]
Fixed by 2add4f6f684e7d68f81f67b6483665896c084a68. This item wasn't meant to be able to target neutral-team characters (e.g. Newt).
