### ISSUE TITLE
All Items Fail To Load

### ISSUE THREAD

**Issue by GalacticRuler** [ThinkInvis/RoR2-TinkersSatchel#6]
### Describe the Bug
This mod causes all items to cease to exist. command interfaces have no items in them, and chests will never spawn.

### Console Log
Will upload log file in a little bit; have to reinstall and run a session to regenerate a log with this mod.

### Additional Context
this does occur with 47 other mods, including Classic Items, installed; however *only* this one causes any issues when installed.

**Comment by GalacticRuler** [comment]
Never mind? Removing and re-adding the mod (not redownloaded) seems to have cause this to...resolve itself?

**Comment by GalacticRuler** [comment]
I was wrong actually. It seems to be inconsistent, rather than constant.
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/6261983/LogOutput.log)

**Comment by GalacticRuler** [comment]
further investigation shows it doesn't matter if this is installed...so...Hmm (did still have Classic Items though)
Could maybe be issues with the dependency library?

**Comment by GalacticRuler** [comment]
Yeah this is VERY inconsistent. Just got a command essence with about 12 assorted white items. Followed by one with all of them!

**Comment by GalacticRuler** [comment]
wonder if this is actually Monster Variants Plus, instead.

**Comment by ThinkInvis** [comment]
I haven't seen this bug yet myself. I _have_ noticed -- with a sample size of 1, so take this with a grain of salt -- that Command droplets may respect the item restrictions (e.g. damage chest only drops damage items) of their original source now.

**Comment by GalacticRuler** [comment]
seems someone else ran into this
it appears to actually be Classic Items causing it, as that's a common denominator between this and that report.

**Comment by ThinkInvis** [comment]
Fixed in recent versions of R2API, and in TILER2 v4.0.6 (which no longer uses ItemDropAPI).
