### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Unknownusername0001** [ThinkInvis/RoR2-TinkersSatchel#7]
I wanted to know if you where going to update your mod for the newest risk of rain 2 update?

**Comment by ThinkInvis** [comment]
Please only use this issues page for specific bug reports and feature requests (e.g. "item X causes unexpected behavior when picked up", "feature Y could use a config option to tweak property Z", "installing this mod alongside this other mod causes these console errors"...).

I update and/or improve my mods when I have the time and effort to spare to do so. This may take a while when I'm busy with other things, such as recently; especially considering that I have nearly 7 published mods (at the time of writing) and can only work on one at a time.
