### ISSUE TITLE
The Bulwark drone MAY be causing a huge lag spike on my pack.

### ISSUE THREAD

**Issue by anartoast** [ThinkInvis/RoR2-TinkersSatchel#74]
The huge lag happens only when i have bulwark drones plus droneman. I think this only started happening when i downloaded the Tinkers.
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/11752356/LogOutput.log)

**Comment by Thresh90** [comment]
judging from what i'm reading, it seems like its the packbox equip that's causing most of the log spam, it happens with me too

**Comment by anartoast** [comment]
weird. i will be sure to never get that again

**Comment by ThinkInvis** [comment]
It's hard to tell what's going on here, but this _may_ have been fixed by 700f44a4a6a91a8341598a87bfac8141b6cb6c3e. Please reopen if the issue persists (ideally without Mystics Items installed -- that was also causing a lot of errors in the provided console log).
