### ISSUE TITLE
Bug: Kintsugi not unlocking when conditions are met

### ISSUE THREAD

**Issue by Xylephony** [ThinkInvis/RoR2-TinkersSatchel#75]
**Issue**:
With 20 items and half broken, the Kintsugi item does not unlock.

**Reproduce**:
I had ICBM, 3 void missiles, one repulsion armor, one void dagger, 4 mochas, and 10 broken watches. The unlock didn't trigger, and from all the documentation I've read 20 items with half broken is all that's needed.

**Log**: [LogOutput.zip](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/11972913/LogOutput.zip)

**Addt'l Info**:
Happened in MP with a much larger mod set (78 total, albeit many are Bepin/R2API plugins) as well, but I scaled down to the bare minimum here for testing as recommended to ensure the issue occurs even with a trim mod list. In those MP tests I also tried to get _just_ 20 watches and break them all at once, and doing that didn't trigger the unlock either.

**Comment by Shiranui-Izayoi** [comment]
Sorry for thread necro.

I would add to this not only does it not seem to unlock. But even if it is manually unlocked it appears that the item does nothing.

As at the very least it isn't causing anything to change in the stats panel of stuff like BetterUI. And even eyeballing it manually with something like 200 white scrap and 50 yellow/red scrap doesn't seem to have the item do anything. I even tried manually breaking something after picking up the item to see if maybe it runs a check on an item being used but nope. Still nothing. 

For reference I gave myself 20 dios and stood still dying over and over to see if it would work and even after all 20 had been used up nothing changed.

I think something is broken with how the mod is trying/attempting to detect broken/consumed items.
