### ISSUE TITLE
Zero boss items dropped if one player dies

### ISSUE THREAD

**Issue by abrenneke** [ThinkInvis/RoR2-TinkersSatchel#78]
## Describe the Bug

If one player dies in a multiplayer session and the boss is killed, no items drop if this mod is installed.

**Comment by smalllbuddy** [comment]
Can confirm issue happens in my games too.

**Comment by Yoctoboy** [comment]
Hey, would it be possible to merge #79? or should someone fork this mod to add this fix in? It can create a softlock with Forgotten Relics
