### ISSUE TITLE
Deprecated Label

### ISSUE THREAD

**Issue by imakunee** [ThinkInvis/RoR2-TinkersSatchel#8]
The mod seems to be working fine however it is tagged as "Deprecated" in r2modman and Thunderstore. I know it's small but it may confuse some people into not giving it a try. Thank you for your work on your mods, they're a major favorite of mine! (especially the mimic)

**Comment by ThinkInvis** [comment]
This is much more relevant to Thunderstore than to this mod -- see https://github.com/ThinkInvis/RoR2-TinkersSatchel/issues/7#issuecomment-832031819. Either way, should be resolved now.
