### ISSUE TITLE
Item Drone problems.

### ISSUE THREAD

**Issue by BlueEarthCat** [ThinkInvis/RoR2-TinkersSatchel#81]
When you put an item that can become an Void item in the drone and hold an Void item, the Void item replicates 15 times.

This is very deadly. 

have an adverse effect on the balance in the game.

Ex) Item drone ( AtG Missile Mk.1 x 3) will give player 45 of  Plasma Shrimp, if player has Plasma Shirimp.

**Comment by ThinkInvis** [comment]
Unable to reproduce.
