### ISSUE TITLE
Items do not appear in game, collection, or unlocks.

### ISSUE THREAD

**Issue by Jcat4609** [ThinkInvis/RoR2-TinkersSatchel#82]
### Describe the Bug
Items cannot be encountered in-game or spawned with DebugToolkit, they do not appear in the collection at all, and achievements show that there is no unlock defined.

### To Reproduce
1. Load Risk of Rain 2 with profile code provided.
2. Enter logbook, and attempt to find the added items.
3. Click into achievements.

### Expected Behavior
Logbook shows shadows of items (or items if they have been collected), achievements should have an item hooked to them.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TinkersSatchel/files/15478208/LogOutput.log)

### Additional Context
Profile code is `018fc2cd-ad86-4ceb-488c-85662c4f071e`.
![image](https://github.com/ThinkInvis/RoR2-TinkersSatchel/assets/45889756/c59d7b66-990e-4a36-bb54-ffe3272cd4c1)
(Edited to actually put the code in the post ._.)

**Comment by PapaKoneko** [comment]
I am having the same issue. Is it something on my end or just a bug with the mod? Has a fix been found?

**Comment by Albhis** [comment]
For me at least, It's not just items, but all content from the mod; Skills, Drones, Items, etc. Simply don't exist while playing the devotion update. I've tried with an empty mod profile with only TS and still nothing.

Just doesn't work with latest game version

**Comment by ThinkInvis** [comment]
This was due to the mod being entirely broken by the Devotion Update. This will be fixed in production sometime soon as I return from hiatus (relevant commits: 35e083b515659f9332fea4def32ed60514b7e74a through 67273cfd36af9fb90a6fdb4474b16152c2546c8e et al).
