### ISSUE TITLE
option to blacklist specific items/tiers from Mimic

### ISSUE THREAD

**Issue by gaforb** [ThinkInvis/RoR2-TinkersSatchel#9]
Currently, mimic can mimic (standalone) ancient scepter which causes weird behaviour when combined with reroll on extra pickup
In general, it would be nice to be able to prevent mimic from copying red/boss/lunar items for balancing reasons

**Comment by DestroyedClone** [comment]
@gaforb As of the most recent update to the ThunderStore, StandaloneAncientScepter uses the existing method `TILER2.FakeInventory.blacklist.Add(itemDef);` to blacklist the item from being chosen by the Mimic.
Though this won't cover the rest of your suggestions.
